### ISSUE TITLE
Twitch.tv

### ISSUE THREAD

**Issue by Mixaill** [Mixaill/awesome-gog-galaxy#1]
ID whitelisting: ❌

**Comment by Danyelalejandro** [comment]
Hello all

Twitch game library has a few years ago. They sold games a few months and they are giving free games to Twitch prime members every month, so their game library keeps increasing. Their library is even bigger than Epic's.
In order to access the library and install the games the PC application is necessary. It does not include achievements, friends or any other info.
Development just be only to read or see the games and install them.
Thank you all for all your efforts. They will be greatly appreciated.

**Comment by nyash-qq** [comment]
I might have a look on it

**Comment by RelativeProgramming** [comment]
I don't know, if it helps, but Playnite (an open-source variant of GOG GLX 2.0) has a Twitch integration.
Maybe that helps...
https://github.com/JosefNemec/Playnite

**Comment by Danyelalejandro** [comment]
I agree with @RelativeProgramming. Maybe in the dll extension of playnite  could be the key to develop the integration of Twitch as well. It would be worth it check it

**Comment by nicknicola** [comment]
Yeah, please, my Twitch library is huge and I would love to see it on Gog.

**Comment by ManOrMonster** [comment]
+1 from me as well.

**Comment by InterestingJohn** [comment]
+1 from me, with all the free games with Twitch Prime, I'm building quite the library in there now.

**Comment by Riku55** [comment]
+1 it's the only decently larger game library on PC I can't import (yet). Would love being able to :)

**Comment by nyash-qq** [comment]
I'm working on it, bu

**Comment by Danyelalejandro** [comment]
Where we can do that? and how?

**Comment by Danyelalejandro** [comment]
Dear @nyash-qq . Please let us know how we can report issue from GLX client and we will do it. Furthermore, it should be highly recommended to check the dll extension of Playnite for this Twitch integration: https://github.com/JosefNemec/Playnite/releases
Maybe it has the key to develop it as well in GOG Galaxy 2.0 without the issue you are mentioning. I am not pretty sure, I am not a good developer, but I do not want to be a leech from you guys of the community that are helping us to have a better experience with these projects. Thank you so muc!!! :)

**Comment by JD557** [comment]
@Danyelalejandro just choose "Report issue" in the settings menu:

<img width="414" alt="Screenshot 2019-08-04 at 15 10 57" src="https://user-images.githubusercontent.com/1187242/62424686-185e6800-b6ca-11e9-818b-6de0f1911792.png">

**Comment by Danyelalejandro** [comment]
Thank you @JD557  Now, what we shold say? that Twitch.tv integration developed by @nyash-qq is not working? to grant permissions to be usable? I am a little lost here. Thank you

**Comment by JD557** [comment]
I believe that this is the problem:

Twitch.tv is not part of the [Platform ID list](https://galaxy-integrations-python-api.readthedocs.io/en/latest/platforms.html#platforms-link), so you there's no platform ID to use for that extension.

**Comment by nyash-qq** [comment]
Here's the initial version https://github.com/nyash-qq/galaxy-plugin-twitch. 

Until Twitch is officially supported by the GLX, before installing the plugin replace `"platform": "twitch"` with any supported platform (tested with `"humble"`) in `galaxy-plugin-twitch/src/manifest.json`

**Comment by Danyelalejandro** [comment]
Thank you guys. I have reported the issue in the app like this: It has been developed an integration for Twitch game library but it is not usable because Twitch.tv is not part of the Platform ID list.
Please include it in the Platform ID list so the extension could be usable.
¿Whatdo you think? ¿It is okay? ¿We all should send this issue as well?

**Comment by Danyelalejandro** [comment]
Another question. I tried to use your initial version but I didn't find the release version and I do not know how to use Python for that. Could you help us with one beta release version, using another platform as yu said? For example POE. Thank you.

**Comment by Danyelalejandro** [comment]
Dear @nyash-qq I am stuck building from source code in the command INV INSTALL. It shows this error:
ModuleNotFoundError: No module named 'galaxy'
I have installed another extensions just by copying official releases to %localappdata%\GOG.com\Galaxy\plugins\installed
Please do a release (just like this example: https://github.com/UncleGoogle/galaxy-integration-humblebundle) or let me know what else I have to do in order to build from source code. Thank you

**Comment by nyash-qq** [comment]
@Danyelalejandro here you go https://github.com/nyash-qq/galaxy-plugin-twitch/releases/tag/0.1

**Comment by Ellathar** [comment]
@nyash-qq thanks, works wonder. I've used platform = amazon and it works well. Great job !

**Comment by InterestingJohn** [comment]
Yep, works for me as well! Great job, now if we could just get GOG to add Twitch as a platform.

**Comment by nyash-qq** [comment]
Not sure if `"amazon"` is supposed to be used for `twitch`, but looks like a better option than using something else like `"humble"`.  I've made it the default one. Thanks @Ellathar. 
Will confirm with GOG if this should stay like that (with `"amazon"`) or a separate platform should be used. Either way, I think we can close this issue.

**Comment by Danyelalejandro** [comment]
Excellent work dear @nyash-qq . Thank you so much. Investigating a little bit I found out that, the only exclusive store of Amazon of PC games was via Twitch, So, it seems indeed is the default platform for Twitch but we hadn't noticed that before. We always talk about Twitch game lubrary, but not Amazon game library.
The client is able to see most of my Twitch Library and to play installed games. Unfortunately doesn't let install them, and the plugin disconnects every time GOG Glaxay 2.0 is closed (different that another plugins). The game Tyranny commander edition game was not detected by client during integration.
I noticed you are a "fixer-developer-client-service" technician as well (because you are helping me with an issue in which Stream plugin crashes permanently) It will be helpful for you to report this an issue via the client?

**Comment by nyash-qq** [comment]
@Danyelalejandro np :)
"Install" seems to be blocked for Amazon by the GLX somehow, as it works if platform is changed to something else.
Auto-reconnect on startup is also a bug in the GLX, but I managed to work-around this in the plugin itself.

We should move the discussion to the appropriate places:
If it is connected to the plugin itself, create an issue here: https://github.com/nyash-qq/galaxy-plugin-twitch/issues/new
Issues with the GLX Client should be reported to the GOG (cogwheel menu -> Report Issue).

**Comment by Danyelalejandro** [comment]
We'll do so. Thank you so much again.

**Comment by Danyelalejandro** [comment]
Guys, this issue is closed but I like to share with you the official answer from GOG about the ID platform:
"Amazon can be used to identify Twitch games. We will be adding Twitch as supported platform into API as well...."
https://mantis2.gog.com/view.php?id=6248#c5918
Thank you dear @nyash-qq and all.

**Comment by JokeDeity** [comment]
How is this not a thing yet?  I have so many games on Twitch.

**Comment by JTNDev** [comment]
But it is a thing, just not officially
https://github.com/nyash-qq/galaxy-plugin-twitch

**Comment by maylortaylor** [comment]
I can't wait for this to be officially part of GOG Galaxy.
I have a lot of Amazon Prime / Twitch games and would love these added to my GOG Galaxy library.

**Comment by sicu** [comment]
I used to have my twitch game library listed in the twitch app, but now they are all gone and I have to use a different launcher called "Amazon Games" to see my game library. Have I been pushed over to this new launcher early, or is this also the case for anyone else in here?

**Comment by xanasago** [comment]
@sicu Interesting. I still have my games in the Twitch App but the updated(had it already for New World) Amazon Launcher has the games also... just that they don't autodetect the already installed games. For a short moment I was excited till I saw that they just added the same bad system into the Amazon Launcher combined with the claim prime loot webpage.
Small change seems they name the game folder with the game name instead of a string of hexadecimal system(I think?). And there is a subfolder with informations about the install. We can't seem to easily(first glance) migrate already installed games because we need some extras and the manifest is not readable.

Maybe they migrated US or some regions early? I am from EU.
