### ISSUE TITLE
Galaxy_Plugin_Bethesda : How to permanently remove this or any unsupported plugin?

### ISSUE THREAD

**Issue by WazBurrows** [Mixaill/awesome-gog-galaxy#125]
** Problem description **

This plugin won't connect to Bethesda because they have shutdown that API and made people transfer their keys to Steam. The problem is that I can't remove the plugin. It won't connect (it just keeps trying) and when I remove the plugin it gets automatically recreated (from the server?) when I start Galaxy again. I've been told it has to successfully connect for you to be able to remove it? Does anyone know how to work around this issue to either fake a successful connection so that it can be removed or make some other change allowing me to remove it and not have the server recreate it?

** Steps to reproduce **

This would be difficult. I installed this plugin when Bethesda was still hosting a game launcher but now it doesn't.  This is a legacy plugin that I can't remove.

** Logs **

n/a

**Comment by UncleGoogle** [comment]
Two methods:

1. write to GOG support. According to RODO you have rights to remove any portion of your data - you can ask them to disconnect this integration for you (because behind local plugin connection there is a information stored in GOG backends)

2. do it yourself (requires Galaxy client) by connecting plugin successfully, then clicking **disconnect** button in Galaxy UI. 

You can trick it for any no longer working plugin that way:
- go to installed plugins directory https://github.com/gogcom/galaxy-integrations-python-api#lookup-directory
- find your plugin
- open main plugin script (usually `plugin.py`) in your favorite text editor
- edit `async def authenticate` method to immediately return a mock Authentication object for example:
```python
async def authenticate(self, stored_credentials=None):
    return Authentication(user_id=12345, user_name="whatever")
```
(note there are 4 spaces, not a tab before "return")
- save file
- restart Galaxy 
(if plugin has crashed, you've broken plugin file syntax -- redownload from github or remove plugin directory and restart Galaxy to let it redownload it for you (works only in case of "popular" plugins))
- conflict prompt will probably be shown, click yes
- if needed -- connect plugin again -- see successful login
- click disconnect

**Comment by WazBurrows** [comment]
Thanks! I'll try this out later and close it "Resolved" if all goes well.

**Comment by WazBurrows** [comment]
Thanks @UncleGoogle. When I came to check again today the plugin had become "Connected", but not really because it was showing there was an error and wanted me to retry.  However, being in the connected state I was able to disconnect it, and then removing the plugin from the plugin folder worked. Although I didn't require the in-depth instructions you provided on how to mockup an authentication object to make the plugin think its connected, this will be invaluable info for anyone else who runs into this issue with an unsupported plugin in the future.
