### ISSUE TITLE
Amazon Games

### ISSUE THREAD

**Issue by anhonorableleech** [Mixaill/awesome-gog-galaxy#84]
**Identification**
Twitch now directs users to download a new app at https://download.amazongames.com/AmazonGamesSetup.exe. It is almost exactly the same interface for installing games as the Twitch app, but it doesn't require the rest of the bloated Twitch client.

**Integration type**
launcher

**Present in [Galaxy API available integrations list]?**
no

**Supported platforms**
PC

**Store content / licenses**
Offers free games and in-game loot through Twitch Prime

**Galaxy features**
- importing owned games
- detect locally installed games / install / launch / uninstall

**Comment by jfmongrain** [comment]
That would be great.  As anhonorableleech mentioned, the Twitch desktop client, despite being functionnal, is very bloated.  The new client is clean and lightweight, and support for it would be very appreciated.

**Comment by AndrewDWhite** [comment]
I have added basic functionality for amazon games to my generic galaxy plugin. Since it is a generic solution it doesn't have the full integration but should hold you over until someone implements a full featured plugin. You will just need to update the amazon section of emulators.json to use the drives that you have your games installed on; if you are not exclusively using your D and G drives fir them.
https://github.com/AndrewDWhite/GalaxyGenericImporterPlugin

**Comment by Rall3n** [comment]
I took some time to create a working plugin for the Amazon Games App.

You can find it here: https://github.com/Rall3n/galaxy-integration-amazon

It still has a slight bug with the installation of games (`Not compatible`), but the rest should be functional.

**Comment by jfmongrain** [comment]
Thank you.  I will be sure to try it and will keep an eye on future developement.
